version: '3.8'

services:
  # Backend API (Port 3000) - Using local PostgreSQL
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: elyx-backend
    environment:
      DATABASE_URL: postgresql://elyx_user:elyx_secure_password_2024@host.docker.internal:5432/elyx_care_chronicle
      NODE_ENV: development
      PORT: 3000
      CORS_ORIGIN: "http://localhost:3001,http://127.0.0.1:3001,http://0.0.0.0:3001"
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./backend/logs:/app/logs

  # Frontend React App (Port 3001)
  frontend:
    build:
      context: ./elyx-care-chronicle-frontend
      dockerfile: Dockerfile
    container_name: elyx-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3000
      GENERATE_SOURCEMAP: "false"
      BROWSER: none
      WDS_SOCKET_HOST: localhost
      WDS_SOCKET_PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    driver: bridge
